spring.application.name=bookstore

#jpa
spring.jpa.show-sql=true

#h2-database
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb

#data rest path
spring.data.rest.base-path=/api